
name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup Node.js 18.17.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.0
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Instalação do Mocha pra testes
      run: |
        cd src;
        npm install -g mocha;
        npm install
